version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/auction/postgresql/data
    environment:
      - POSTGRES_DB=auction
      - POSTGRES_USER=andrey
      - POSTGRES_PASSWORD=password
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/auction
    ports:
      - "8000:8000"
    depends_on:
      - db