# Generated by Django 2.2.23 on 2021-05-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='lot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bet.Lot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
